language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true  EXTRA_DEB="ros-hydro-pr2eus ros-hydro-joint-state-publisher" ROS_PARALLEL_JOBS="-j2 -l2"
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true  EXTRA_DEB="ros-indigo-pr2eus  ros-indigo-joint-state-publisher" ROS_PARALLEL_JOBS="-j8"
script: source .travis/travis.sh
notifications:
  email:
    on_success: always
    on_failure: always
